# image will be published to ghcr.io/<user>/<name>
name: hyprland
# description will be included in the image's metadata
description: ublue images for wayland compositors

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - from-file: common-packages.yml

  - type: rpm-ostree
    install:
      - hyprland
      - waybar # wayland status bar
      - xdg-desktop-portal-hyprland # hyprland fork of xdg-desktop-portal-wlr with additional features such as screensharing
      
      # wayland utilities
      - swaybg # allows setting wallpaper in hyprland config file
     
      # essentials for usability
      - xdg-desktop-portal-hyprland
      - qt5-qtwayland # qt wayland support
      - qt6-qtwayland # qt wayland support

      # improved desktop experience
      - pavucontrol # audio control and device switching through pipewire integration

      # additional GUI applications
      - lxappearance # set icons/themes for GTK 2
      - qt5ct # qt5 settings configuration (themes, font, icons, etc)
      - qt6ct # qt6 settings configuration (themes, font, icons, etc)
      

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
