# image will be published to ghcr.io/<user>/<name>
name: river
# description will be included in the image's metadata
description: ublue images for wayland compositors

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common-packages.yml
  - from-file: common-files.yml

  - type: files
    files:
      - river/usr: /usr 

  - type: rpm-ostree
    install:
      - river
      - waybar
      - xdg-desktop-portal-wlr


  - from-file: common-scripts.yml
  - type: signing
