# image will be published to ghcr.io/<user>/<name>
name: hyprland
# description will be included in the image's metadata
description: ublue images for wayland compositors

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - from-file: common-packages.yml

  - type: rpm-ostree
    install:
      - hyprland
      - waybar
      - xdg-desktop-portal-hyprland
      - xorg-x11-server-Xwayland

      # wayland utilities
      - swaybg
      - swayidle
      - swaylock
      - wlr-randr
      - wl-sunset

      # essentials for usability
      - pipewire
      - wireplumber
      - xdg-desktop-portal-hyprland
      - xdg-user-dirs
      - polkit-kde
      - qt5-qtwayland
      - qt6-qtwayland

      # improved desktop experience
      - bluez
      - bluez-tools
      - blueman
      - network-manager-applet
      - pavucontrol

      # additional GUI applications
      - thunar
      - lxappearance
      - qt5ct
      - qt6ct
      

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
