name: build-wayblue
on:
  schedule:
    - cron: "00 4 * * *" # build at 4:00 UTC every day 
                          # (20 minutes after last ublue images start building)
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build wayblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - recipe-sway.yml
          - recipe-sway-nvidia.yml
          - recipe-hyprland.yml
          - recipe-hyprland-nvidia.yml
          - recipe-river.yml
          - recipe-river-nvidia.yml
          - recipe-wayfire.yml
          - recipe-wayfire-nvidia.yml
          - recipe-sway-gdm.yml
          - recipe-sway-nvidia-gdm.yml
          - recipe-hyprland-gdm.yml
          - recipe-hyprland-nvidia-gdm.yml
          - recipe-river-gdm.yml
          - recipe-river-nvidia-gdm.yml
          - recipe-wayfire-gdm.yml
          - recipe-wayfire-nvidia-gdm.yml
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Add yq (for reading recipe.yml)
        uses: mikefarah/yq@v4.44.3

      - name: Gather image data from recipe
        run: |
          echo "IMAGE_NAME=$(yq '.name' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_VERSION=$(yq '.image-version' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
          BASE_IMAGE=$(yq '.base-image' ./recipes/${{ matrix.recipe }})
          echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV


      - name: Build wayblue
        uses: blue-build/github-action@v1.6.1
        with:
          cli_version: v0.8.20
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          squash: true
